version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/expense_manager
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - STORAGE_PATH=/app/storage  # Define una variable de entorno para la ruta
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage  # Monta la carpeta local en el contenedor
    command: poetry run uvicorn template.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expense_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 