# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build

on:
  push:
    branches: [ '*' ]
    paths:
      - 'src/**'
      - 'tests/**'

  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'src/**'
      - 'tests/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make ci-prebuild
          make build
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          make cover
      - name: Build Image
        run: |
          docker build . --file Dockerfile --tag template:PR-${{ github.event.number }}